### ISSUE TITLE
ACNH 7PM/6PM (sunny only?) unique incompatibility

### ISSUE THREAD

**Issue by FoilGear** [ic-scm/automatic-bars-patcher#1]
Having the 6 PM hourlies (from ACNH) renamed to instead play at 7 PM, causes broken audio playback, with no apparent differences in the file known, having checked in HxD, _even if said files are converted to .wav, then back to .bwav._
In-game, it sounds like both channels of stereo are playing the same song at different points. Shortly after this occurs, the game softlocks/freezes & crashes, along with audio stuttering.
The ACNH 5 PM playing at 6 PM plays normally, maybe worth noting?
Any conversions I did were done using openrevolution, I have not experienced any other crashes using other tracks during 7PM, or otherwise to my memory.

https://user-images.githubusercontent.com/45780976/105933938-400f6180-601d-11eb-8884-82b843cd3012.mp4

**Comment by ic-scm** [comment]
I do not have this issue when replacing the 7PM themes with the files from 6PM in ACNH version 1.6.0. Are you sure you have the correct original BARS and BWAV files, and is there anything else I should know? Does the patcher not show any warnings or errors?

The same behavior could happen if the 7PM tracks were not patched at all, the only thing I can think of right now that could cause this issue is accidentally renaming the files in their original dumped location.
